name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build:
    # needs to be run on a macos machine because of KT/Native apple targets
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build & Publish to Maven Central
      env:
        MAVEN_URL: ${{ secrets.MAVEN_URL }}
        MAVEN_USER: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASS: ${{ secrets.OSSRH_PASSWORD }}
      run: |
        ./gradlew
        -PsigningKey=${{ secrets.SIGNING_KEY }}
        -PsigningPassword=${{ secrets.SIGNING_PASSWORD }}
        build publish
    
    - name: Get current version
      id: get_version
      run: |
        ./gradlew properties -q | grep "version:" | awk '{print $2}'

    - name: Add GitHub tag
      if: github.ref == 'refs/heads/main'
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ steps.get_version.outputs.stdout }}
        prerelease: false
        draft: false
