name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build:
    # needs to be run on a macos machine because of KT/Native apple targets
    runs-on: macos-latest
    permissions: 
      contents: write # for automatic tag creation

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Set up Konan (KT/Native) cache
      uses: actions/cache@v2
      with:
        path: ~/.konan/cache
        key: ${{ runner.os }}-konan

    - name: Build & Publish to Maven Central
      env:
        MAVEN_URL: ${{ secrets.MAVEN_URL }}
        MAVEN_USER: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASS: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      run: |
        ./gradlew build publish 

    - name: Get current version
      id: get_version
      run: |
        ./gradlew properties -q | grep "version:" | awk '{print $2}' > version.txt
        echo JB_VERSION=$(cat version.txt) >> $GITHUB_OUTPUT

    - name: Add GitHub tag
      if: github.ref == 'refs/heads/main'
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ steps.get_version.outputs.JB_VERSION }}
        prerelease: false
        draft: false

    - name: Close staging repository # If everything succeeds, auto-publish to Maven Central
      if: success()
      run: |
        ./gradlew closeAndReleaseRepository
